import Link from "next/link";
import React from "react";
import { ArrowLeft, Github, ExternalLink, BookOpen, Brain, Shield, Cpu } from "lucide-react";

export default function JailbreakLLM() {
  return (
    <div className="bg-gradient-to-tl from-black via-zinc-600/20 to-black">
      <div className="min-h-screen px-6 pt-16 mx-auto space-y-8 max-w-7xl lg:px-8 md:space-y-16 md:pt-24 lg:pt-32">
        <div className="mx-auto lg:mx-0">
          <Link
            href="/projects"
            className="duration-200 text-zinc-400 hover:text-zinc-100"
          >
            <ArrowLeft className="w-6 h-6" />
          </Link>
        </div>

        <div className="w-full mx-auto lg:mx-0">
          <div className="flex items-center gap-4 mb-6">
            <Brain className="w-8 h-8 text-zinc-400" />
            <h1 className="text-3xl font-bold tracking-tight text-zinc-100 sm:text-4xl">
              Jailbreak LLM Response Classifier
            </h1>
          </div>
          
          <p className="mt-4 text-zinc-400 text-lg">
            Bachelor's Thesis Project - University of Milano-Bicocca
          </p>
          
          <div className="flex items-center gap-2 mt-2 text-sm text-zinc-500">
            <span>Supervisors: Prof. Claudio Ferretti, Prof.ssa Martina Saletta</span>
          </div>
        </div>

        <div className="w-full h-px bg-zinc-800" />

        <div className="grid grid-cols-1 gap-8 mx-auto lg:grid-cols-2">
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold text-zinc-100 mb-4 flex items-center gap-2">
                <BookOpen className="w-5 h-5" />
                Project Overview
              </h2>
              <p className="text-zinc-400 leading-relaxed">
                Detection and analysis of responses generated by language models under adversarial prompts. 
                This project addresses the challenge of automatically detecting when an LLM response results 
                from a jailbreak prompt, combining supervised learning with unsupervised analysis.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-zinc-100 mb-3 flex items-center gap-2">
                <Shield className="w-5 h-5" />
                Key Features
              </h3>
              <ul className="space-y-2 text-zinc-400">
                <li className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-2 flex-shrink-0"></span>
                  <span>Binary Classification with fine-tuned BERT model</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-2 flex-shrink-0"></span>
                  <span>Embedding Extraction using [CLS] token embeddings</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-2 flex-shrink-0"></span>
                  <span>Unsupervised Clustering (K-means & Hierarchical)</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-2 flex-shrink-0"></span>
                  <span>Dimensionality Reduction with PCA, t-SNE, and UMAP</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-zinc-400 mt-2 flex-shrink-0"></span>
                  <span>Fully containerized Google Colab notebooks</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-zinc-100 mb-3 flex items-center gap-2">
                <Cpu className="w-5 h-5" />
                Technical Stack
              </h3>
              <div className="flex flex-wrap gap-2">
                {["Python", "BERT", "Transformers", "scikit-learn", "PyTorch", "Google Colab", "Jupyter"].map((tech) => (
                  <span
                    key={tech}
                    className="px-3 py-1 text-xs bg-zinc-800 border border-zinc-700 rounded-md text-zinc-300"
                  >
                    {tech}
                  </span>
                ))}
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-zinc-100 mb-3">
                Methodology
              </h3>
              <div className="space-y-3 text-zinc-400">
                <div className="p-4 bg-zinc-800/50 rounded-lg border border-zinc-700">
                  <h4 className="font-medium text-zinc-200 mb-2">Fine-tuned BERT Classification</h4>
                  <p className="text-sm">Labels responses as jailbreak or non-jailbreak with confidence scores for thresholding analysis.</p>
                </div>
                <div className="p-4 bg-zinc-800/50 rounded-lg border border-zinc-700">
                  <h4 className="font-medium text-zinc-200 mb-2">Clustering Analysis</h4>
                  <p className="text-sm">Free K-means with optimal k determination and hierarchical clustering for multi-level grouping.</p>
                </div>
                <div className="p-4 bg-zinc-800/50 rounded-lg border border-zinc-700">
                  <h4 className="font-medium text-zinc-200 mb-2">Visualization</h4>
                  <p className="text-sm">2D plots using PCA, t-SNE, and UMAP to assess cluster separation and structure.</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="w-full h-px bg-zinc-800" />

        <div>
          <h3 className="text-lg font-semibold text-zinc-100 mb-4">
            Project Structure
          </h3>
          <div className="bg-zinc-900/50 rounded-lg p-6 border border-zinc-800">
            <pre className="text-sm text-zinc-400 overflow-x-auto">
{`LLM_Response_Classifier/
├── CODE/
│   ├── FINAL_VERSIONS/
│   │   ├── free_clustering/
│   │   └── hierarchical_clustering/
│   └── PREVIOUS_STEPS/
├── DATASETS/
│   ├── fine_tuning_and_test/
│   └── kmeans_evaluation/
├── reports_and_findings/
└── FINAL_REPORT/`}
            </pre>
          </div>
        </div>

        <div className="flex gap-4 pt-8">
          <Link
            href="#"
            className="flex items-center gap-2 px-4 py-2 text-sm bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-md text-zinc-300 transition-colors duration-200"
          >
            <Github className="w-4 h-4" />
            View Code
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-4 py-2 text-sm bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 rounded-md text-zinc-300 transition-colors duration-200"
          >
            <ExternalLink className="w-4 h-4" />
            Live Demo
          </Link>
        </div>
      </div>
    </div>
  );
}